//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsaSignalRSocket.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRateOfInterestOfBank
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool IsPublished { get; set; }
        public int TimePeriodId { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> BaseCurve { get; set; }
        public Nullable<decimal> FractionRate { get; set; }
        public Nullable<decimal> RateOfInterest { get; set; }
        public string GroupIds { get; set; }
        public Nullable<decimal> FractionRate2 { get; set; }
        public Nullable<decimal> RateOfInterest2 { get; set; }
        public Nullable<decimal> FractionRate3 { get; set; }
        public Nullable<decimal> RateOfInterest3 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
