//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsaWebAPI.Persistance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForsaEntities : DbContext
    {
        public ForsaEntities()
            : base("name=ForsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCustomerGroup> tblCustomerGroups { get; set; }
        public virtual DbSet<tblGroup> tblGroups { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
        public virtual DbSet<tblPage> tblPages { get; set; }
        public virtual DbSet<tblRatingAgeNtur> tblRatingAgeNturs { get; set; }
        public virtual DbSet<tblSalutation> tblSalutations { get; set; }
        public virtual DbSet<tblTimePeriod> tblTimePeriods { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
