//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsaWebAPI.persistance.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepositInsurance
    {
        public int DepositInsuranceId { get; set; }
        public string DepositInsurance { get; set; }
    }
}
