//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsaWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForsaEntities : DbContext
    {
        public ForsaEntities()
            : base("name=ForsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblLanguage> tblLanguages { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
