//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForsaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmptbl
    {
        public string TimePeriod { get; set; }
        public string Bank { get; set; }
        public decimal RateOfInterest { get; set; }
        public int SrNo { get; set; }
    }
}
